steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
      - gcloud
      - container
      - clusters
      - get-credentials
      - prevvy
      - --zone=us-central1-b
  - name: 'gcr.io/k8s-skaffold/skaffold'
    args:
      - skaffold
      - run
      - -f=skaffold.yaml
      - -p
      - develop